version: '3.4'

services:
  hds.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - OAuth__Google__ClientId=${OAUTH_GOOGLE_CLIENT}
      - OAuth__Google__ClientSecret=${OAUTH_GOOGLE_SECRET}
      - ConnectionStrings__DefaultConnection=${PGSQL_CONNECTION}
      - Logging__LogLevel__Default=Trace
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  hds.db:
    environment:
      - POSTGRES_USER=${PGSQL_USER_NAME}
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
      - POSTGRES_DB=${PGSQL_DEV_DB_NAME}
    ports:
      - "${PGSQL_PORT}:${PGSQL_PORT}"
    volumes:
      - .\pgdata:/var/lib/postgresql/data
      - .\init:/docker-entrypoint-initdb.d