version: '3.4'

services:
  hds_client:
    image: mikhailgodunko/hds.client
    depends_on: 
     - hds_server

  hds_server:
    image: ${DOCKER_REGISTRY-}hds_server
    container_name: hds_server
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    networks:
      - hds_network
    depends_on:
      - hds_db

  hds_db:
    image: postgres
    container_name: hds_db
    networks:
      - hds_network


networks: 
  hds_network:
    driver: bridge