<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Pages\Common\Paragraph.razor" />
    <AdditionalFiles Include="Pages\Home\Home.razor" />
    <AdditionalFiles Include="Pages\Home\SectionBlock.razor" />
    <AdditionalFiles Include="Pages\DescriptionPages\DescriptionPage.razor" />
    <AdditionalFiles Include="Pages\DescriptionPages\WoodenStructures.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Pages\Blog\BlogLinkBlock.razor.css.map" />
    <None Remove="Pages\Blog\Blog.razor.css.map" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>

</Project>
