name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
    - uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore ./HDS.sln

    - name: Build project
      run: dotnet build --no-restore ./HDS.sln
    
    - name: Push builded files to cache
      uses: actions/cache/save@v3
      with:
        key: build-cache
        path: ./

  test:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Load builded files from cache
      uses: actions/cache/restore@v3
      with:
        key: build-cache
        path: ./
  
    - name: Test
      run: dotnet test --no-build --verbosity normal ./HDS.sln
      

  docker_build:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f ./src/Server/Dockerfile .
    
    - name: Save image to file
      run: |
        mkdir -p cache/docker
        docker save $LOGIN/$NAME:${GITHUB_REF:11} > cache/docker/docker-image.tar
    
    - name: Push image file to cache
      uses: actions/cache/save@v3
      with:
        key: docker-image-cache
        path: cache/docker/docker-image.tar

  docker_pub:
    needs: [docker_build]
    
    runs-on: ubuntu-latest
    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
      
    steps:
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    
    - name: Create folder for cahe
      run: mkdir -p cache/docker

    - name: Load image file from cache
      uses: actions/cache/restore@v3
      with: 
        key: docker-image-cache
        path: cache/docker/docker-image.tar

    - name: Load image from file
      run: docker load < cache/docker/docker-image.tar

    - name: Push image to docker.io
      run: docker push $LOGIN/$NAME:${GITHUB_REF:11}


